version: '3.8'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=TodoProject.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/TodoDB
    ports:
      - "8000:8000"
    user: "1000:1000"  # Запуск от непривилегированного пользователя
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: TodoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_volume:
  db_data: